# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegate < Formula
  desc "Remotely manage Claude Code sessions via Telegram"
  homepage "https://github.com/ljdongz/codegate"
  version "0.1.0"
  license "MIT"

  depends_on "bun"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.0/codegate_darwin_amd64.tar.gz"
      sha256 "9b84ff71fe0ad6daeb6bc8e156b596e766616c79a87dc4bb02e477ba824958c7"

      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.0/codegate_darwin_arm64.tar.gz"
      sha256 "a1973197a0309b3d22a0ff745838491228f69d75380b964a0fec38e1ee3cb449"

      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.0/codegate_linux_amd64.tar.gz"
      sha256 "ca1279ba1e8aaa91344488e15a48910758b9e98a95f7137fb6158969b4537c5d"
      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.0/codegate_linux_arm64.tar.gz"
      sha256 "b27140646625025ed48053fa70c0f67422ce4fbebeceab1e1ebdb068e4a966fa"
      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  test do
    system "#{bin}/codegate", "--help"
  end
end
