# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegate < Formula
  desc "Remotely manage Claude Code sessions via Telegram"
  homepage "https://github.com/ljdongz/codegate"
  version "0.1.3"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.3/codegate_darwin_amd64.tar.gz"
      sha256 "7439e3f428a6d1fba670e1267cb4ef8f38dbef0c9f503276c1fab8f96bebb7d1"

      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.3/codegate_darwin_arm64.tar.gz"
      sha256 "01277575989dc3e0e251a1f42bc1e571455a848c0bdc0041a5b7d205851d31a0"

      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.3/codegate_linux_amd64.tar.gz"
      sha256 "461736d84f93e013493afc0f8f5cac56ba157b77b5f7b06e14eb9cf494dcb68a"
      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.3/codegate_linux_arm64.tar.gz"
      sha256 "1b93ada45dc267830f713cd022eec4bab77bad80bc0314ad0c126dbb3a1caf75"
      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  test do
    system "#{bin}/codegate", "--help"
  end
end
