# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codegate < Formula
  desc "Remotely manage Claude Code sessions via Telegram"
  homepage "https://github.com/ljdongz/codegate"
  version "0.1.1"
  license "MIT"

  depends_on "bun"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.1/codegate_darwin_amd64.tar.gz"
      sha256 "c4596eca55771156ff885f68eafd09a4e36cc16d029b3738cfed1a55e0f5853b"

      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.1/codegate_darwin_arm64.tar.gz"
      sha256 "b74217372d6018db5170af88e95b612bcd1a0f143206e3cc2c153842a7e48992"

      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.1/codegate_linux_amd64.tar.gz"
      sha256 "308ff44381aa90539a1b57144f82fa6d43b90f0b63fd57af9ae8c0afc4450fe3"
      define_method(:install) do
        bin.install "codegate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljdongz/codegate/releases/download/v0.1.1/codegate_linux_arm64.tar.gz"
      sha256 "ce0ee252cb29504264025222100e8dc6e2680a4a1041be9b4d8cb1f843f0d26e"
      define_method(:install) do
        bin.install "codegate"
      end
    end
  end

  test do
    system "#{bin}/codegate", "--help"
  end
end
